name: CI

on:
  push:
    brances: [ main ]
  pull_request:
    brances: [ main ]

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and export
      uses: docker/build-push-action@v5
      with:
        context: .
        tags: mp-build:latest
        outputs: type=docker,dest=/tmp/mp-build.tar
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: mp-build
        path: /tmp/mp-build.tar

  test-and-coverage:
    runs-on: ubuntu-latest
    needs: build-image
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Download image artifact
      uses: actions/download-artifact@v3
      with:
        name: mp-build
        path: /tmp
    - name: Load image
      run: docker load --input /tmp/mp-build.tar
    - name: Run unit tests
      run: docker run --rm -v "$(pwd)":/code -w /code mp-build:latest make test
    - name: Measure coverage
      run: docker run --rm -v "$(pwd)":/code -w /code mp-build:latest make coverage
    - name: Coverage summary JSON upload
      uses: actions/upload-artifact@v4
      with:
        name: coverage-summary
        path: ./test/coverage_summary.json
    - name: Update https://gist.github.com/LassiHeikkila/2cc186f7491127168e70d457b16fe950
      uses: exuanbo/actions-deploy-gist@v1
      with:
        token: ${{ secrets.COVERAGE_GIST_TOKEN }}
        gist_id: 2cc186f7491127168e70d457b16fe950
        gist_file_name: coverage_summary.json
        file_path: ./test/coverage_summary.json
